model:
  optimizer : 'adadelta' # adadelta adam SGD
  lr : 0.001 # to do : adaptive lr
  epochs : 1000
  epoch : 1
  momentum : 0.9 # for SGD

  iteration : 0
  patience : 5 # for early stopping
  log_interval : 10

  seed : 1234  # random seed
  batch_size : 20 #100
  test_batch_size: 10
  arc : 'ResNet'

  #sound setting
  window_size : 0.01   # 0.02
  window_stride : 0.01 # 0.01
  window_type : 'hamming'
  normalize : True